### ISSUE TITLE
掉线了无法重连

### ISSUE THREAD

**Issue by yihanyuan** [Ultronxr/robot#2]
没搞过类似的项目，找了好久找到这个能看懂且适配最新版的，但是放到服务器上，过个十几分钟机器人掉线之后不会重连，不知道啥原因下面是日志，出现Logging in  就没了动静了，想知道是什么原因导致的怎么解决，谢谢

[0m2021-02-21 13:44:24 V/Net 171296949: Send: Heartbeat.Alive[0m
[0m2021-02-21 13:44:24 V/Net 171296949: Recv: Heartbeat.Alive.Response[0m
[0m2021-02-21 13:48:54 V/Net 171296949: Send: Heartbeat.Alive[0m
[0m2021-02-21 13:48:54 V/Net 171296949: Recv: Heartbeat.Alive.Response[0m
[0m2021-02-21 13:53:24 V/Net 171296949: Send: Heartbeat.Alive[0m
[0m2021-02-21 13:53:24 V/Net 171296949: Recv: Heartbeat.Alive.Response[0m
[0m2021-02-21 13:53:38 V/Net 171296949: Send: OnlinePush.RespPush[0m
[0m2021-02-21 13:53:47 V/Net 171296949: Send: OnlinePush.RespPush[0m
[0m2021-02-21 13:56:33 V/Net 171296949: Channel closed.[0m
[92m2021-02-21 13:56:33 I/Net 171296949: Logging in...[0m
[92m2021-02-21 13:56:33 I/Net 171296949: Logging in...[0m

**Comment by Ultronxr** [comment]
可以参阅一下这个掉线问题的 [官方discussions](https://github.com/mamoe/mirai/discussions/985) 
目前 `mirai.version` 更新至 `2.4.0` ，暂时没有遇到掉线的情况

**Comment by yihanyuan** [comment]
之前加了join没效果，我试下单独new一个线程启动机器人看看会怎么样

**Comment by yihanyuan** [comment]
> 可以参阅一下这个掉线问题的 [官方discussions](https://github.com/mamoe/mirai/discussions/985)
> 目前 `mirai.version` 更新至 `2.4.0` ，暂时没有遇到掉线的情况

之前加了join没效果，我试下单独new一个线程启动机器人看看会怎么样

**Comment by Ultronxr** [comment]
排查之后是我的代码问题，查看一下这次[commit记录](https://github.com/Ultronxr/robot/commit/5fda193ae33559b521963f989d6dc65214a100cf) ，mirai掉线会自动重登，我在重登事件（`botReloginHandler()`方法）里的代码画蛇添足了
